[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
alxblock_program = "AANa17EN5vqdUPwtc9hqZ7FZLqPNRZMbbc5cydDGRMCi"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
